name = "CallMode"
uuid = "58f4d5cc-129e-49a8-ab65-a421196c1a3b"
authors = ["AntonOresten <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0"

[deps]
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
ReplMaker = "0.2"
Setfield = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
