name = "CallMode"
uuid = "58f4d5cc-129e-49a8-ab65-a421196c1a3b"
authors = ["AntonOresten <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
